name: Deploy Pipline

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**/*"
      - "!**/README.md"
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
    working-directory: ./
  
jobs:
  setup-envvironment:
    runs-on: ubuntu-latest
    name: set up evnvironment
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Terraform fmt
        id: fmt
        run: |
            terraform fmt -check -chdir=./terrafrom
      
      - name: Terraform Init
        id: init
        run: |
          terraform init -chdir=./terrafrom
      
      - name: Terraform Validate
        id: validate
        run: |
          terraform validate -no-color -chdir=./terrafrom
      
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -chdir=./terrafrom