name: hello world

on:
  push:
    branches:
      - "main"
    paths:
      - './**'
      - '!./README.md/**'
  pull_request:
    branches:
      - "main"
    paths:
      - './**'
      - '!./README.md/**'

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello
        run: echo "hello"
        shell: bash

  word:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: world
        run: echo "world"
        shell: bash
